const QUOTES = [
["Small progress every day builds up to big results.", "— StudySpark"],
["Start with five focused minutes; momentum will follow.", "— StudySpark"],
["Don’t wait for motivation. Create the routine.", "— StudySpark"],
["Consistency beats intensity when you’re building skills.", "— StudySpark"],
["Study like you mean it, rest like you earned it.", "— StudySpark"],
["One solved problem is better than ten half-started ones.", "— StudySpark"],
["Focus on process, not outcomes.", "— StudySpark"],
["Break big tasks into 25-minute sprints.", "— StudySpark"],
["Reading is the shortest path to thinking clearly.", "— StudySpark"],
["Replace ‘I’ll do it later’ with ‘I’ll do 10 minutes now.’", "— StudySpark"],
["Plan your study, then study your plan.", "— StudySpark"],
["Active recall beats passive reading.", "— StudySpark"],
["Sleep is part of the study routine.", "— StudySpark"],
["Consistency compounds knowledge.", "— StudySpark"],
["A focused mind is a powerful tool.", "— StudySpark"],
["Mistakes are proof you’re trying.", "— StudySpark"],
["Break your work into small victories.", "— StudySpark"],
["Prioritize understanding, not memorization.", "— StudySpark"],
["Review yesterday, learn today, plan tomorrow.", "— StudySpark"],
["Your brain works best after short breaks.", "— StudySpark"],
["Write it down to remember it.", "— StudySpark"],
["Start difficult tasks first.", "— StudySpark"],
["Quality over quantity in study hours.", "— StudySpark"],
["Ask questions, don’t just read answers.", "— StudySpark"],
["Teaching someone else helps retention.", "— StudySpark"],
["Set measurable goals for each session.", "— StudySpark"],
["Eliminate distractions before you start.", "— StudySpark"],
["Use visual aids to reinforce learning.", "— StudySpark"],
["Practice makes permanent.", "— StudySpark"],
["Consistency > intensity.", "— StudySpark"],
["Learning is a marathon, not a sprint.", "— StudySpark"],
["Chunk large topics into smaller parts.", "— StudySpark"],
["Focus on one topic at a time.", "— StudySpark"],
["Explain concepts aloud to yourself.", "— StudySpark"],
["Use spaced repetition for long-term memory.", "— StudySpark"],
["Active engagement beats passive reading.", "— StudySpark"],
["Motivation follows action, not precedes it.", "— StudySpark"],
["Minimize multitasking while studying.", "— StudySpark"],
["Reflect on what you learned each day.", "— StudySpark"],
["Reward progress, not perfection.", "— StudySpark"],
["Study with purpose, not habit.", "— StudySpark"],
["Ask why, not just what.", "— StudySpark"],
["Keep a tidy study environment.", "— StudySpark"],
["Visualize the end goal.", "— StudySpark"],
["Take notes in your own words.", "— StudySpark"],
["Use past papers to test understanding.", "— StudySpark"],
["Set realistic daily study targets.", "— StudySpark"],
["Track your progress consistently.", "— StudySpark"],
["Change subjects to maintain focus.", "— StudySpark"],
["Simplify complex ideas.", "— StudySpark"],
["Write summaries after each session.", "— StudySpark"],
["Practice under exam conditions.", "— StudySpark"],
["Study actively, not passively.", "— StudySpark"],
["Organize your notes logically.", "— StudySpark"],
["Teach the material to an imaginary student.", "— StudySpark"],
["Use mnemonic devices for tricky concepts.", "— StudySpark"],
["Turn mistakes into learning opportunities.", "— StudySpark"],
["Study when your mind is freshest.", "— StudySpark"],
["Set specific time blocks for study.", "— StudySpark"],
["Review before sleep for better retention.", "— StudySpark"],
["Keep challenging yourself progressively.", "— StudySpark"],
["Ask questions even if they seem simple.", "— StudySpark"],
["Focus on understanding concepts fully.", "— StudySpark"],
["Write practice answers to reinforce learning.", "— StudySpark"],
["Summarize each topic in your own words.", "— StudySpark"],
["Break long study sessions with mini breaks.", "— StudySpark"],
["Study with intention, not distraction.", "— StudySpark"],
["Active problem solving beats passive reading.", "— StudySpark"],
["Create diagrams to visualize complex topics.", "— StudySpark"],
["Revise regularly to keep knowledge fresh.", "— StudySpark"],
["Don’t cram; space out your learning.", "— StudySpark"],
["Stay consistent, even with small sessions.", "— StudySpark"],
["Combine reading with hands-on practice.", "— StudySpark"],
["Focus on quality, not quantity of study hours.", "— StudySpark"],
["Ask ‘how’ and ‘why’ questions.", "— StudySpark"],
["Use different sources to strengthen understanding.", "— StudySpark"],
["Keep track of weak areas for targeted revision.", "— StudySpark"],
["Prioritize tasks using importance and urgency.", "— StudySpark"],
["Set micro-goals for each study session.", "— StudySpark"],
["Reflect on learning methods regularly.", "— StudySpark"],
["Write down formulas and definitions to memorize.", "— StudySpark"],
["Connect new knowledge to what you already know.", "— StudySpark"],
["Test yourself frequently, don’t just read notes.", "— StudySpark"],
["Stay hydrated and healthy to boost focus.", "— StudySpark"],
["Practice time management for study sessions.", "— StudySpark"],
["Eliminate unnecessary distractions.", "— StudySpark"],
["Switch subjects to avoid mental fatigue.", "— StudySpark"],
["Use flashcards for rapid review.", "— StudySpark"],
["Prioritize understanding over rote memorization.", "— StudySpark"],
["Keep a positive mindset while studying.", "— StudySpark"],
["Track your study streaks for motivation.", "— StudySpark"],
["Do short daily reviews of old material.", "— StudySpark"],
["Explain topics to a friend or peer.", "— StudySpark"],
["Use color-coding to organize notes.", "— StudySpark"],
["Write questions and answer them yourself.", "— StudySpark"],
["Focus on one task at a time.", "— StudySpark"],
["Avoid studying late at night when tired.", "— StudySpark"],
["Set a specific goal for each study session.", "— StudySpark"],
["Turn boring material into a challenge.", "— StudySpark"],
["Review mistakes in practice exercises.", "— StudySpark"],
["Stay disciplined even when motivation dips.", "— StudySpark"],
["Keep your study space clean and organized.", "— StudySpark"],
["Use diagrams to simplify complex ideas.", "— StudySpark"],
["Reflect on what techniques worked best.", "— StudySpark"],
["End each study session with a short summary.", "— StudySpark"],
["Focus on understanding, not memorization.", "— StudySpark"],
["Take regular short breaks to refresh your mind.", "— StudySpark"],
["Review key points at the end of the day.", "— StudySpark"],
["Practice problems without looking at solutions first.", "— StudySpark"],
["Use spaced repetition for difficult topics.", "— StudySpark"],
["Write down everything you’ve learned.", "— StudySpark"],
["Ask yourself how you would teach it.", "— StudySpark"],
["Use mind maps to connect ideas.", "— StudySpark"],
["Summarize each chapter in 3–5 sentences.", "— StudySpark"],
["Read actively and highlight key concepts.", "— StudySpark"],
["Avoid passive rereading of notes.", "— StudySpark"],
["Challenge yourself with higher-level questions.", "— StudySpark"],
["Set up a study schedule and stick to it.", "— StudySpark"],
["Stay consistent even on low-energy days.", "— StudySpark"],
["Practice previous exam papers.", "— StudySpark"],
["Check your understanding by explaining aloud.", "— StudySpark"],
["Review errors immediately to learn from them.", "— StudySpark"],
["Take care of your body to support mental performance.", "— StudySpark"],
["Set goals that are challenging but achievable.", "— StudySpark"],
["Prioritize tasks for maximum learning impact.", "— StudySpark"],
["Use visual aids to remember abstract concepts.", "— StudySpark"],
["Write down questions to research later.", "— StudySpark"],
["Break large topics into small, manageable chunks.", "— StudySpark"],
["Avoid multitasking while studying.", "— StudySpark"],
["Stay curious; curiosity drives learning.", "— StudySpark"],
["Keep a notebook for reflections and insights.", "— StudySpark"],
["End study sessions with review and reflection.", "— StudySpark"],
["Reward yourself for progress, not perfection.", "— StudySpark"],
["Practice active recall, not passive reading.", "— StudySpark"],
["Teach what you learn to reinforce memory.", "— StudySpark"],
["Keep learning fun to stay motivated.", "— StudySpark"],
["Focus on the logic behind concepts.", "— StudySpark"],
["Use simple language when taking notes.", "— StudySpark"],
["Avoid cramming; distribute learning over time.", "— StudySpark"],
["Track your progress to stay accountable.", "— StudySpark"],
["Switch subjects to maintain engagement.", "— StudySpark"],
["Review summaries regularly to retain information.", "— StudySpark"],
["Use checklists to track daily study tasks.", "— StudySpark"],
["Keep a consistent study environment.", "— StudySpark"],
["Use diagrams and flowcharts for visualization.", "— StudySpark"],
["Summarize complex topics in simple terms.", "— StudySpark"],
["Ask ‘why’ to deepen understanding.", "— StudySpark"],
["Focus on one study goal at a time.", "— StudySpark"],
["Reflect on learning strategies and improve them.", "— StudySpark"],
["Prioritize your mental and physical well-being.", "— StudySpark"],
["Take notes in your own words.", "— StudySpark"],
["Break long sessions with mini physical breaks.", "— StudySpark"],
["Use past papers and exercises frequently.", "— StudySpark"],
["Eliminate distractions before starting.", "— StudySpark"],
["Review difficult concepts multiple times.", "— StudySpark"],
["Stay disciplined and consistent.", "— StudySpark"],
["End sessions on a positive.","— StudyPark"]
];
